name: Dependency Bot Auto Merge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && (github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'main')
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs (minor/patch)
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  renovate:
    runs-on: ubuntu-latest
    if: (github.event.pull_request.user.login == 'app/renovate' || github.event.pull_request.user.login == 'renovate[bot]') && (github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'main')
    steps:
      - name: Enable auto-merge for Renovate PRs
        run: gh pr merge --auto --merge --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
